server:
  # 服务端口号
  port: 8082
spring:
  application:
    name: user-server
  datasource:
    url: jdbc:mysql://localhost:3306/test?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

# mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*.xml # mapper映射文件位置
  type-aliases-package: com.lih.userserver.entity # 实体类所在的位置

eureka:
  client:
    service-url:
      # 填写注册中心服务器地址
      defaultZone: http://lihui:lihui@127.0.0.1:8081/eureka
    # 是否需要将自己注册到注册中心
    register-with-eureka: true
    # 是否需要搜索服务信息
    fetch-registry: true
  instance:
    # 使用ip地址注册到注册中心
    prefer-ip-address: true
    # 注册中心列表中显示的状态参数
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

logging:
  level:
    #查看sql运行语句
    com.lih.userserver.mapper : debug
