server:
  #端口号
  port: 8081

spring:
  security:
    user:
      name: lihui
      password: lihui


eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8081/eureka # eureka服务地址
    register-with-eureka: false # 由于该应用为注册中心, 所以设置为false, 代表不向注册中心注册自己
    fetch-registry: false #由于注册中心的职责就是维护服务实例, 它并不需要去检索服务, 所以也设置为 false
